services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: jirb
      MONGO_INITDB_ROOT_PASSWORD: rahasia
      MONGO_INITDB_DATABASE_ADMIN: admin
